### ISSUE TITLE
Formulas disappeared after server migration (PHP 7.4.10)

### ISSUE THREAD

**Issue by magmage** [liffiton/dokuwiki-plugin-mathjax#33]
After a server migration from PHP 5.6.40 to PHP 7.4.10 the MathJax plugin stopped working. While the MathJax JS loads fine the whole LaTeX environments are deleted entirely from the produced HTML files. I suspect something in 'syntax_plugin_mathjax_protecttex' goes wrong in the new PHP version and removes the LaTeX environments instead of protecting them. Any help is appreciated.

PS: This issue+fix could be related: https://stackoverflow.com/questions/43242929

**Comment by liffiton** [comment]
Hmm.  I don't have this issue with PHP 7.3.19.  This may be hard for me to reproduce.

The issue you've found does match in many respects, but I don't think the problem is the same.  `preg_replace()` isn't used in this MathJax plugin, and I expect the deprecated "/e" modifier isn't used anywhere in the Dokuwiki code at this point, either.

Do you have any other plugins installed?  If so, could you try temporarily disabling them to see if any of them are contributing to the problem?

Have you changed any of the MathJax plugin configuration options from the defaults?

**Comment by magmage** [comment]
Thank you a lot for this really quick reply. So here is what I tried now:

- made sure that I use only the default plugin configuration: no effect
- disabled all other plugins: Bingo!

So I went back step-by-step to find out which plugin causes the (newfound) issue and identified it as "plugin:latexit". So I switched to the much more recent "plugin:latexport" instead that works in the exact same way and my day was saved.

Thank's again for the quick reply + helpful suggestions.
