### ISSUE TITLE
mhchem extension broken

### ISSUE THREAD

**Issue by TheManchineel** [liffiton/dokuwiki-plugin-mathjax#39]
I want to add chemical formulas and equations to my Wiki. I'm using the MathJax plugin with the following configuration:

```
MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [ ["$","$"], ["\\(","\\)"] ],
        displayMath: [ ["$$","$$"], ["\\[","\\]"] ],
        processEscapes: true
    },
    TeX: {
        equationNumbers: {autoNumber: "AMS"},
        extensions: ["AMSmath.js","AMSsymbols.js","mhchem.js","noErrors.js","noUndefined.js"]
    }
});
```

However, it seems that the plugin isn't working quite properly: when, for example I type a reaction with text above the arrow like so:
`$\ce{Zn_{(s)} + Cu^{2+}_{(aq)} ->[{H_2O}] Zn^{2+}_{(aq)} + Cu_{(s)}}$`
I get this:
[https://imgur.com/aSubnbH](https://imgur.com/aSubnbH)

while in reality I should be getting this, as rendered by KaTeX with mhchem in Joplin:
[https://imgur.com/8kBdNMx](https://imgur.com/8kBdNMx)

And this isn't the only odd behavior. Another example: `<=>` renders as "⇔" while instead it should render as "⇌".

Does anyone have an idea why mhchem is "working" but not quite with MathJax?

**Comment by liffiton** [comment]
It appears to be caused by some substitutions added by [this commit](https://github.com/liffiton/dokuwiki-plugin-mathjax/commit/58cc79e52b8b8fe4d95fc3e5aa460d27b98f8fa4).  That was claimed to be part of supporting latex export in the LaTeXit plugin, but considering it in light of this issue, I'm not sure the substitutions are needed or correct.

I'll remove those substitutions and release a new version of the plugin.

Thanks for the report!

**Comment by TheManchineel** [comment]
@liffiton confirming that this was fully fixed with the new release. Thanks a lot!

**Comment by liffiton** [comment]
Great!  Thanks for the confirmation.
