### ISSUE TITLE
render content in <math> tags

### ISSUE THREAD

**Issue by jakebiesinger** [liffiton/dokuwiki-plugin-mathjax#9]
Hi!

I recently converted over a bunch of mediawiki sites which use the <math> tag to render latex formulas.  Is there a config setting to also register this tag?

Thanks!

**Comment by liffiton** [comment]
It's a long time coming, but I just added a simple ability to specify custom tags to be "protected" from dokuwiki's rendering so they can be rendered by MathJax.  It requires adding the delimiter to the MathJax configuration manually, so it's not fully automatic, but it is an easy setup and should work fine.  The fix is in commit 7d96d4ae.
